version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  borrowings:
    build:
      context: ./Borrowings
      dockerfile: ./Borrowings/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 32768:8080
    restart: always

volumes:
  db:
    driver: local
