version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  borrowings:
    build:
      context: ./Borrowings
      dockerfile: ./Borrowings/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 32768:8080

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 5050:80
volumes:
  db:
    driver: local
